- README.md
Enter was not rendered in markdown (it thinks it's a html tag)
> Fix printing of keybindings in README.md

- README.md
- lua/nvim-treesitter-playground.lua
- lua/nvim-treesitter-playground/query_linter.lua
- plugin/nvim-treesitter-playground.vim
- queries/query/query-linter-queries.scm
First draft for a query linter
I plan to actually parse top-level queries to see whether nvim accepts them. 
TODO:
> Add a query linter module

- queries/query/query-linter-queries.scm
This lints also top-level queries like:
```scheme
((foo))
```
> fix(linter): Add (grouping) to toplevel-queries

- README.md
- lua/nvim-treesitter-playground.lua
- lua/nvim-treesitter-playground/hl-info.lua
- lua/nvim-treesitter-playground/internal.lua
- lua/nvim-treesitter-playground/printer.lua
- lua/nvim-treesitter-playground/query.lua
- lua/nvim-treesitter-playground/query_linter.lua
- lua/nvim-treesitter-playground/utils.lua
- plugin/nvim-treesitter-playground.vim
- syntax/tsplayground.vim
This integrates injected languages into the playground. It adds new features as well.
- Toggle display of the language that the node belongs to
- Toggle display of anonymous nodes
- Nested languages can be "focused". The query editor will run queries on the focused language tree. It is not possible to run queries across multiple languages.
- Toggle display of injected languages. This will turn off processing for injected languages.
- Various bug fixes
> refactor(printer): integrate injected languages

- lua/nvim-treesitter-playground/query_linter.lua
This will enable the linter to recognize LaTeX commands like
`\usepackage` though it will appear as `"\\usepackage"` in the
query files.
> fix: unescape anonymous nodes with escape sequences

- lua/nvim-treesitter-playground/hl-info.lua
Fixes #37 
Added the following improvements:
* use the active highlighter captures instead of reparsing the file:
* uses all active treesitter queries. For a lua file for example, this will also include **comment** queries
* active queries also includes any user queries
* when the treesitter highlight module is not enabled in the buffer, we show the syntax highlight groups instead
* prettier formatting of the popup window using a border and markdown
* shows original and linked highlight groups
> feat: improved TSHighlightCapturesUnderCursor

- lua/nvim-treesitter-playground/query_linter.lua
This together with https://github.com/nvim-treesitter/nvim-treesitter/pull/1495
will make playground work with ecma and html tags
> Use ft_to_lang in guess_query_lang

- lua/nvim-treesitter-playground/utils.lua
Closes https://github.com/nvim-treesitter/playground/issues/33
We should report this to neovim as well (https://github.com/neovim/neovim/issues/14998)
> Avoid crash: check if the buffer is loaded before calling win_findbuf

- lua/nvim-treesitter-playground/internal.lua
- lua/nvim-treesitter-playground/utils.lua
The playground will try to set the cursor
to an invalid position (nvim_win_set_cursor) if the node starts at the EOF mark.
```ruby
def run
a = <<~EOF
end
```
found this while debugging https://github.com/nvim-treesitter/nvim-treesitter/issues/1531
> Playground: check for nodes out of range (EOF)

- lua/nvim-treesitter-playground/internal.lua
Tiny edit to fix keybinds not working when used with some vim config mappings, see issue #52. Credit goes to @waldson for finding the fix :+1:
> playground keybindings no longer recursive, fixes #52

- lua/nvim-treesitter-playground/hl-info.lua
This code depended on an internal cache that stored the names,
but it was changed to store the id https://github.com/neovim/neovim/commit/2460f0a7028550ea2d87492a4e8b95914fdba7b1.
There is `nvim_get_hl_by_id`, but that doesn't return the name (just the
final values of the colors). So, I'm just duplicating this part https://github.com/neovim/neovim/blob/6a92a53c02c429630c4b961e51dc97f3354ea196/runtime/lua/vim/treesitter/highlighter.lua#L81-L93
Fixes https://github.com/nvim-treesitter/playground/issues/60
> Fix local hl on `:TSHighlightCapturesUnderCursor`

- lua/nvim-treesitter-playground/internal.lua
Otherwise this will default to the current buffer, which may not be the same buffer where the query is.
Fixes https://github.com/nvim-treesitter/playground/issues/53
> Pass the query_bufnr explicitly to get_node_text

- lua/nvim-treesitter-playground.lua
- lua/nvim-treesitter-playground/hl-info.lua
- lua/nvim-treesitter-playground/internal.lua
- lua/nvim-treesitter-playground/query_linter.lua
- plugin/nvim-treesitter-playground.lua
- plugin/nvim-treesitter-playground.vim
I would appreciate some testing for regressions since I don't use nearly all features of the Playground (in particular, the query editor and linter).
I could not remove all legacy vimscript since the keymappings are created using string munging, and Lua doesn't have a macro system that would allow similar things natively:
https://github.com/nvim-treesitter/playground/blob/13e2d2d63ce7bc5d875e8bdf89cb070bc8cc7a00/lua/nvim-treesitter-playground/internal.lua#L214
> feat!: update to Neovim 0.7 APIs

- lua/nvim-treesitter-playground/utils.lua
This is a stop-gap fix to avoid errors on latest master after https://github.com/neovim/neovim/pull/19931
Closes #89 
This at least gives useful information (the capture name, albeit without leading `@`), but a full rewrite is needed once nvim-treesitter decides on how to handle the upstream changes to highlight group names. 
Chances are the whole functionality can be removed after 0.8 is released.
> fix: adapt to breaking change on master

- lua/nvim-treesitter-playground/internal.lua
https://github.com/nvim-treesitter/playground/pull/105 broke highlighting of captures under the cursor in the `query_editor`.
i'm guessing some of the other calls to the upstream `get_node_text` introduced in the pr might have to be adjusted, but i don't the codebase / treesitter well enough to say.
> fix: use current buf for get_node_text in on_query_cursor_move

- README.md
#74 added `:TSNodeUnderCursor`, but this isn't mentioned anywhere on the README. This PR helps to increase visibility of this functionality.
EDIT: oops, just saw #104 plans to remove the two exposed commands. Not sure when `:Inspect` will stabilize, if it is soon, then feel free to close this PR.
> docs: mention `:TSNodeUnderCursor` in readme

- lua/nvim-treesitter-playground/query_linter.lua
This fixes the error where out-of-tree queries are annotated with errors due to different directory structures
see https://github.com/NixOS/nixpkgs/issues/189838#issuecomment-1380814689
the screenshot in the original comment is from https://github.com/tree-sitter/tree-sitter-scala, and the query file is under a directory named `queries`, which is not a valid language name, and this pull request silently ignores it
> fix: peacefully ignore query files without a valid language

- README.md
This is a result of the discussion in https://github.com/nvim-treesitter/playground/pull/111
TLDR query linter makes some assumptions about the directory structure which should be explicitly stated in the documentation.
> Add note about query linter assumptions

- lua/nvim-treesitter-playground/internal.lua
- lua/nvim-treesitter-playground/query.lua
- lua/nvim-treesitter-playground/query_linter.lua
- lua/nvim_treesitter_playground_query_omnifunc.lua
> fix: Rename deprecated `vim.treesitter` calls

- lua/nvim-treesitter-playground/query_linter.lua
This PR fixes an issue that was mentioned in the following comment.
https://github.com/nvim-treesitter/playground/issues/119#issuecomment-1501048844
> fix pcall of vim.treesitter.language.inspect

- lua/nvim-treesitter-playground/internal.lua
- lua/nvim-treesitter-playground/query_linter.lua
PR #120 used nvim-treesitter.compat in some occasions but not all: https://github.com/nvim-treesitter/playground/pull/120/files
This made nvim-treesitter-playground incompatible with older Neovim versions https://github.com/nvim-treesitter/playground/pull/120#issuecomment-1509140602
Although, we generally only support latest Neovim stable this is a unnecessary inconsistency in the code base. Also when, ts_compat should be removed in future it should there will be only one source of `get_node_text` that can then be swapped consistently around the whole code base. nvim-treesitter-playground is especially useful for older Neovim versions that don't have the built-in playground yet.
@wookayin
> fix: only have one source of `get_node_text` (nvim-treesitter.compat)
