nvim-treesitter/playground

README.md, lua/nvim-treesitter-playground.lua, lua/nvim-treesitter-playground/internal.lua, lua/nvim-treesitter-playground/utils.lua, plugin/nvim-treesitter-playground.vim
=> feat(playground): add toggle command

README.md, lua/nvim-treesitter-playground.lua, lua/nvim-treesitter-playground/internal.lua
I always want to press `<enter>` to go to the current node in AST in the code buffer. Don't know whether this keymap can be added...
=> Enter keymap

lua/nvim-treesitter-playground.lua, lua/nvim-treesitter-playground/internal.lua, lua/nvim-treesitter-playground/printer.lua, lua/nvim-treesitter-playground/query.lua
thanks extmarks :)
wip because we might want to disable that feature by default, it's a little bit heavy on the eyes.
=> [WIP] Hl group for each node !

lua/nvim-treesitter-playground.lua, lua/nvim-treesitter-playground/hl-info.lua
=> feat: add `TSHighlightCapturesUnderCursor` to show hl matches under cursor

lua/nvim-treesitter-playground/hl-info.lua, lua/nvim-treesitter-playground/printer.lua, lua/nvim-treesitter-playground/query.lua
Preliminary fix for change in languagetree API
=> Fix playground for languagetree API change

lua/nvim-treesitter-playground/internal.lua, lua/nvim-treesitter-playground/printer.lua, lua/nvim-treesitter-playground/utils.lua
=> fix(highlight): fix owning tree highlighting

lua/nvim-treesitter-playground/internal.lua
=> fix(buf): toggle buf window from tree window

lua/nvim-treesitter-playground/internal.lua
=> fix(query): get named nodes when not displaying anonymous nodes

lua/nvim-treesitter-playground/internal.lua
I introduced some weird indentation
=> Config key fixup

lua/nvim-treesitter-playground/hl-info.lua
Ref: https://nvim-treesitter.zulipchat.com/#narrow/stream/252274-plugin.2Fnvim-treesitter/topic/gdscript.20bugs/near/235024462
=> Make clear that upper-case captures map directly to vim hl-groups

README.md
Not a lot of people are aware that this functionality exists in the playground, so I would suggest to include it in the REAME.
=> docs: added docs about TSHighlightCapturesUnderCursor

README.md, lua/nvim-treesitter-playground/internal.lua
Ref https://github.com/nvim-treesitter/playground/issues/23
=> Hint how to use the query editor

queries/query/query-linter-queries.scm
This is to match https://github.com/nvim-treesitter/tree-sitter-query/pull/15
=> Query linter: update queries

lua/nvim-treesitter-playground/hl-info.lua
- show priority
- show both syntax and tree-sitter if both are enabled
=> Improvements for TSHighlightCapturesUnderCursor

lua/nvim-treesitter-playground.lua, lua/nvim-treesitter-playground/hl-info.lua
=> feat: add TSNodeUnderCursor

lua/nvim-treesitter-playground/internal.lua
=> fixup: use new api for keymap

lua/nvim-treesitter-playground/hl-info.lua
currently if treesitter-highlighter is not loaded and there is no syntax available, `:TSCaptureUnderCursor` throws an error; this commit makes sure that no empty array is passed into `open_floating_preview`.
additionally `show_hl_captures` will now try to query the highlight group even if `vim.b.current_syntax == nil` as a fallback
this is useful inside buffers that manage their own highlight groups (nvim-tree, neogit, etc)
=> fix(fallback for show_hl_captures)

lua/nvim-treesitter-playground/hl-info.lua, lua/nvim-treesitter-playground/utils.lua
=> fix: update tree-sitter mappings

lua/nvim-treesitter-playground/internal.lua
=> fix: handle errors in query editor

lua/nvim-treesitter-playground/internal.lua, lua/nvim-treesitter-playground/query_linter.lua
=> chore: replace deprecated ts_utils.get_node_text

README.md
https://github.com/nvim-treesitter/playground/issues/88#issuecomment-1373019566
=> docs: mention `query` grammar in requirements

lua/nvim-treesitter-playground/printer.lua
=> fix: highlight groups are off by one

lua/nvim-treesitter-playground.lua, lua/nvim-treesitter-playground/query_linter.lua
The last commit also removes the older `use_virtual_text` option, I can drop this if you want to keep it
=> feat(query_linter): add new option use_diagnostics

lua/nvim-treesitter-playground/hl-info.lua, lua/nvim-treesitter-playground/utils.lua
fix: https://github.com/nvim-treesitter/nvim-treesitter/pull/4300
=> fix: rename ts_utils.is_in_node_range -> vim.treesitter.is_in_node_range
